services:
  flask: 
    build: .
    ports:
      - "8000:5000" # Mappe le port hôte 8000 sur le port conteneur 5000
    volumes:
      # Montage du répertoire courant dans /app
      - .:/app 
    environment:
      - FLASK_APP=app.py       # Point d'entrée de l'application
      - FLASK_DEBUG=1          # Activation du mode debug 
      # URL de connexion à la base de données
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb 

  db:
    # Configuration de la base de données PostGIS
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    # Configuration de l'interface pgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pg_data:
  pgadmin_data: